# Generated by Django 4.0.4 on 2022-04-21 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('world_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('curr', models.BooleanField(default=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('truck_id', models.AutoField(primary_key=True, serialize=False)),
                ('cur_status', models.CharField(choices=[('i', 'IDLE'), ('t', 'TRAVELING'), ('l', 'LOADING'), ('d', 'DELIVERING')], max_length=30, null=True)),
                ('pos_x', models.CharField(max_length=30, null=True)),
                ('pos_y', models.CharField(max_length=30, null=True)),
                ('world', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='myUPS.world')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('wh_id', models.CharField(max_length=30, null=True)),
                ('wh_addr_x', models.CharField(max_length=30, null=True)),
                ('wh_addr_y', models.CharField(max_length=30, null=True)),
                ('dest_x', models.CharField(max_length=30, null=True)),
                ('dest_y', models.CharField(max_length=30, null=True)),
                ('cur_status', models.CharField(choices=[('p', 'wait for pick up'), ('o', 'out for delivery'), ('d', 'delivered')], max_length=30, null=True)),
                ('ready_for_pickup_time', models.CharField(max_length=30, null=True)),
                ('load_time', models.CharField(blank=True, max_length=30, null=True)),
                ('delivered_time', models.CharField(max_length=30, null=True)),
                ('truck', models.ForeignKey(max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='myUPS.truck')),
                ('user', models.ForeignKey(max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='myUPS.account')),
                ('world', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='myUPS.world')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='world',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='myUPS.world'),
        ),
    ]
