version: '2'

services:
  main:
    build: ./src
    command: bash -c "/code/run.sh"
    volumes:
      - /var/log/erss:/var/log/erss:rw
      - ./src:/code
    ports:
      - "12345:12345"
    tty: true
