# Generated by Django 4.0.1 on 2022-01-28 00:53

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0002_choice_question_remove_vehicle_owner_delete_ride_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.CharField(default='open', max_length=20)),
                ('destination', models.CharField(max_length=50)),
                ('arrival_date', models.DateTimeField()),
                ('passenger_num', models.IntegerField()),
                ('is_sharable', models.BooleanField(default=False)),
                ('vehicle', models.CharField(blank=True, max_length=15)),
                ('special_request', models.CharField(blank=True, max_length=50)),
                ('driver_id', models.IntegerField(blank=True, default=-1)),
                ('rider_order_id', models.IntegerField(default=-1)),
                ('sharer_id', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None)),
                ('sharer_passengers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None)),
                ('total_passenger_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_driver', models.BooleanField(default=False)),
                ('vehicle_type', models.CharField(blank=True, max_length=15)),
                ('plate_num', models.CharField(blank=True, max_length=15)),
                ('max_passengers', models.IntegerField(blank=True, default=1)),
                ('special_vehicle_info', models.CharField(blank=True, default='', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
