# Generated by Django 4.0.1 on 2022-01-31 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0007_auto_20220131_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_full',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ride_order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(default=-2022),
        ),
    ]
